version: '3.5'
services:
  web:
    image: 'microblogpub:latest'
    ports:
     - "${WEB_PORT}:5005"
    volumes:
     - "${CONFIG_DIR}:/app/config"
     - "./static:/app/static"
    environment:
     - MICROBLOGPUB_MONGODB_HOST=${COMPOSE_PROJECT_NAME}_mongo_1:27017
     - MICROBLOGPUB_DEBUG=1
     - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
     - POUSSETACHES_AUTH_KEY=123
  mongo:
    image: "mongo:latest"
  poussetaches:
    image: "poussetaches:latest"
    environment:
     - POUSSETACHES_AUTH_KEY=123
networks:
  default:
    name: microblogpubfede 
